site_name: PL/SQL & SQL Coding Guidelines
site_url: https://trivadis.github.io/plsql-and-sql-coding-guidelines/

repo_name: trivadis/plsql-and-sql-coding-guidelines
repo_url: https://github.com/trivadis/plsql-and-sql-coding-guidelines
edit_uri: ""

theme:
  logo: images/trivadis-logo.svg
  icon:
    repo: fontawesome/brands/github-alt
  name: 'material'
  custom_dir: custom-theme
  favicon: images/favicon.ico
  palette:
    primary: 'white'
    accent: 'red'

extra_css:
  - 'stylesheets/extra.css'
  - 'css/version-select.css'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'js/version-select.js'
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
      linenums_style: table
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - footnotes

extra:
  guideline_version: 4.1
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Trivadis
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/trivadis

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
